# Generated by Django 5.0.1 on 2024-06-12 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minds', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
