/**
 * Writes src/shared/hanVariants.ts, the table the Citation check folds
 * traditional Chinese characters into simplified ones with (ADR-0009), from
 * OpenCC's character table, TSCharacters.txt, in the opencc-data package
 * (Apache-2.0, a devDependency): `node scripts/hanVariants.ts`.
 * tests/shared/hanVariants.test.ts checks the table against the package.
 *
 * Characters only, never phrases. Each traditional character maps to its
 * first simplified one, followed to the end of a chain ("薴" to "苧" to "苎"),
 * so folding twice is folding once; a character whose first is itself is
 * left out. Both must be one UTF-16 code unit, so offsets into the text hold.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

/** The pairs, as "traditional simplified" strings, from TSCharacters.txt's text. */
export function hanVariantPairs(text: string): string[] {
  const first = new Map<string, string>();
  for (const line of text.split("\n")) {
    if (!line.trim() || line.startsWith("#")) continue;
    const [from = "", to = ""] = line.split("\t");
    const target = to.trim().split(" ")[0] ?? "";
    if (from.length !== 1 || target.length !== 1 || target === from) continue;
    first.set(from, target);
  }
  const pairs: string[] = [];
  for (const [from, to] of first) {
    let end = to;
    for (const seen = new Set([from]); first.has(end) && !seen.has(end); ) {
      seen.add(end);
      end = first.get(end) as string;
    }
    if (end !== from) pairs.push(`${from}${end}`);
  }
  return pairs.sort();
}

/** TSCharacters.txt as the installed opencc-data has it, and that package's version. */
export function tsCharacters(): { version: string; text: string } {
  const require = createRequire(import.meta.url);
  const dir = dirname(require.resolve("opencc-data/package.json"));
  const { version } = JSON.parse(readFileSync(join(dir, "package.json"), "utf8"));
  return { version, text: readFileSync(join(dir, "data", "TSCharacters.txt"), "utf8") };
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const { version, text } = tsCharacters();
  const pairs = hanVariantPairs(text);
  const lines: string[] = [];
  for (let at = 0; at < pairs.length; at += 32) lines.push(`  "${pairs.slice(at, at + 32).join("")}",`);
  writeFileSync(
    join(root, "src", "shared", "hanVariants.ts"),
    `/**
 * Traditional Chinese characters and the simplified ones the Citation check
 * folds them into (ADR-0009), as pairs: ${pairs.length} of them. Generated by
 * scripts/hanVariants.ts from TSCharacters.txt of OpenCC (Open Chinese
 * Convert), in the opencc-data package ${version}, Apache-2.0.
 * Don't edit it by hand.
 */
const PAIRS = [
${lines.join("\n")}
].join("");

/** Each traditional character's simplified one; characters that aren't traditional aren't in it. */
export const SIMPLIFIED: ReadonlyMap<string, string> = new Map(
  Array.from({ length: PAIRS.length / 2 }, (_, index) => [
    PAIRS[index * 2] as string,
    PAIRS[index * 2 + 1] as string,
  ]),
);
`,
  );
  console.log(`${pairs.length} pairs from opencc-data ${version}`);
}
