name: Build Docker Container & Push to Registry

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test_django_job:
    uses: junruxiong/Incarnamind-Backend/.github/workflows/test-django.yaml@main
  docker_build:
    runs-on: ubuntu-latest
    needs: [test_django_job]
    env:
      CLUSTER_NAME: incarna-k8s

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}"
      # - name: Set up gcloud SDK
      #   uses: google-github-actions/setup-gcloud@v1

      - name: Azure login
        id: login
        uses: azure/login@v1.4.3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Azure Container Registry login
        run: |
          az acr login --name ${{ secrets.REGISTRY }}
      - name: Set AKS context
        id: set-context
        uses: azure/aks-set-context@v3
        with:
          resource-group: "${{ secrets.resource_group }}"
          cluster-name: "${{ secrets.cluster_name }}"
      - name: Setup kubectl
        id: install-kubectl
        uses: azure/setup-kubectl@v3
      - name: Build container image
        run: |
          docker build --tag django:latest .
      - name: Manually tag the built image with custom tags
        run: |
          docker tag django:latest incarnaregistry.azurecr.io/django:${GITHUB_SHA::7}-${GITHUB_RUN_ID::5}
      - name: Push all tagged images to the registry
        run: |
          docker push incarnaregistry.azurecr.io/django --all-tags

      - name: Create Kubernetes secret for GCP
        env:
          GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        run: |
          echo "$GCP_SERVICE_ACCOUNT_KEY" > /tmp/gcp-key.json
          kubectl create secret generic gcp-service-account-key --from-file=keyfile.json=/tmp/gcp-key.json --dry-run=client -o yaml | kubectl apply -f -
      - name: Update deployment secrets
        run: |
          if kubectl get secrets | grep -q django-prod-env; then
          kubectl delete secret django-prod-env
          fi
          cat << EOF >> ./.env.prod
          AUTH_COOKIE_SECURE=${{ secrets.AUTH_COOKIE_SECURE }}
          AWS_SES_ACCESS_KEY_ID=${{ secrets.AWS_SES_ACCESS_KEY_ID }}
          AWS_SES_FROM_EMAIL=${{ secrets.AWS_SES_FROM_EMAIL }}
          AWS_SES_REGION_NAME=${{ secrets.AWS_SES_REGION_NAME }}
          AWS_SES_SECRET_ACCESS_KEY=${{ secrets.AWS_SES_SECRET_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AZURE_ACCOUNT_KEY=${{ secrets.AZURE_ACCOUNT_KEY }}
          AZURE_ACCOUNT_NAME=${{ secrets.AZURE_ACCOUNT_NAME }}
          AZURE_ACCOUNT_CONN_STRING=${{ secrets.AZURE_ACCOUNT_CONN_STRING }}
          CELERY_FLOWER_PASSWORD=${{ secrets.CELERY_FLOWER_PASSWORD }}
          CELERY_FLOWER_USER=${{ secrets.CELERY_FLOWER_USER }}
          CLUSTER_NAME=${{ secrets.CLUSTER_NAME }}
          CUSTOM_HOSTNAME=${{ secrets.CUSTOM_HOSTNAME }}
          DATABASE_ENGINE=${{ secrets.DATABASE_ENGINE }}
          DATABASE_HOST=${{ secrets.DATABASE_HOST }}
          DATABASE_NAME=${{ secrets.DATABASE_NAME }}
          DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}
          DATABASE_USER=${{ secrets.DATABASE_USER }}
          DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}
          FRONTEND_HOSTNAME=${{ secrets.FRONTEND_HOSTNAME }}
          GOOGLE_AUTH_KEY=${{ secrets.GOOGLE_AUTH_KEY }}
          GOOGLE_AUTH_SECRET_KEY=${{ secrets.GOOGLE_AUTH_SECRET_KEY }}
          REDIRECT_URLS=${{ secrets.REDIRECT_URLS }}
          REDIS_HOST=${{ secrets.REDIS_HOST }}
          REDIS_PORT=${{ secrets.REDIS_PORT }}
          REGISTRY=${{ secrets.REGISTRY }}
          RESOURCE_GROUP=${{ secrets.RESOURCE_GROUP }}
          WEBSITE_HOSTNAME=${{ secrets.WEBSITE_HOSTNAME }}
          VECTOR_DB_URL=${{ secrets.VECTOR_DB_URL }}
          VECTOR_DB_API_KEY=${{ secrets.VECTOR_DB_API_KEY }}
          OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
          AZURE_OPENAI_ENDPOINT=${{ secrets.AZURE_OPENAI_ENDPOINT }}
          AZURE_OPENAI_API_KEY=${{ secrets.AZURE_OPENAI_API_KEY }}
          ANTHROPIC_API_KEY=${{ secrets.ANTHROPIC_API_KEY }}
          CO_API_URL=${{ secrets.CO_API_URL }}
          CO_API_KEY=${{ secrets.CO_API_KEY }}
          VOYAGE_API_KEY=${{ secrets.VOYAGE_API_KEY }}
          SPLADE_DOC_URL=${{ secrets.SPLADE_DOC_URL }}
          SPLADE_DOC_KEY=${{ secrets.SPLADE_DOC_KEY }}
          DJANGO_SUPERUSER_USERNAME=${{ secrets.DJANGO_SUPERUSER_USERNAME }}
          DJANGO_SUPERUSER_PASSWORD=${{ secrets.DJANGO_SUPERUSER_PASSWORD }}
          DJANGO_SUERPUSER_EMAIL=${{ secrets.DJANGO_SUERPUSER_EMAIL }}
          EOF
          kubectl create secret generic django-prod-env --from-env-file=./.env.prod
      - name: Refresh k8s deployment
        run: |
          kubectl apply -f kubernetes/redis/deployment.yaml
          kubectl apply -f kubernetes/django/deployment.yaml
          kubectl apply -f kubernetes/celery/beat-deployment.yaml
          kubectl apply -f kubernetes/celery/worker-deployment.yaml
          kubectl apply -f kubernetes/flower/deployment.yaml
      - name: Update Deployment image
        run: |
          kubectl set image deployment/incarna-app incarna-app=incarnaregistry.azurecr.io/django:${GITHUB_SHA::7}-${GITHUB_RUN_ID::5}
          kubectl set image deployment/celery-beat celery-beat=incarnaregistry.azurecr.io/django:${GITHUB_SHA::7}-${GITHUB_RUN_ID::5}
          kubectl set image deployment/celery-worker celery-worker=incarnaregistry.azurecr.io/django:${GITHUB_SHA::7}-${GITHUB_RUN_ID::5}
          kubectl set image deployment/celery-flower celery-flower=incarnaregistry.azurecr.io/django:${GITHUB_SHA::7}-${GITHUB_RUN_ID::5}
      - name: Get Deployment status
        run: |
          kubectl rollout status deployment/incarna-app
          kubectl rollout status deployment/celery-beat
          kubectl rollout status deployment/celery-worker
          kubectl rollout status deployment/celery-flower
      - name: Post-build Django Commands - Migrate / Collectstatic
        run: |
          export SINGLE_POD_NAME=$(kubectl get pod -l app=incarna-app -o jsonpath="{.items[0].metadata.name}")
          kubectl exec -it $SINGLE_POD_NAME -- python manage.py migrate
          kubectl exec -it $SINGLE_POD_NAME -- python manage.py collectstatic --noinput
