name: Rollout Incarna Deployment

on:
  workflow_call:
  workflow_dispatch:

jobs:
  rollout:
    runs-on: ubuntu-latest
    env:
      CLUSTER_NAME: incarna-k8s

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Azure login
        id: login
        uses: azure/login@v1.4.3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        id: set-context
        uses: azure/aks-set-context@v3
        with:
          resource-group: "${{ secrets.resource_group }}"
          cluster-name: "${{ secrets.cluster_name }}"

      - name: Setup kubectl
        id: install-kubectl
        uses: azure/setup-kubectl@v3

      - name: Run rollout on Deployment
        run: |
          kubectl rollout restart deployment/incarna-app
          kubectl rollout restart deployment/celery-worker
