# Generated by Django 5.0.1 on 2024-03-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='token_count',
            field=models.IntegerField(default=0),
        ),
    ]
