apiVersion: batch/v1
kind: Job
metadata:
  name: incarna-staticfiles
spec:
  template:
    spec:
      containers:
        - name: incarna-app
          image: incarnaregistry.azurecr.io/django:latest
          command: ["python", "manage.py", "collectstatic", "--noinput"]
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: django-prod-env
      restartPolicy: Never
  backoffLimit: 5
