# Generated by Django 5.0.1 on 2024-05-11 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='credits',
            field=models.IntegerField(default=100),
        ),
    ]
