# Generated by Django 5.0.1 on 2024-05-12 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_useraccount_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='current_model',
            field=models.CharField(default='gpt35', max_length=255),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='openai_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='max_tokens',
            field=models.IntegerField(default=500000),
        ),
    ]
