# Generated by Django 5.0.1 on 2024-05-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_useraccount_current_model_useraccount_openai_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='current_model',
            field=models.CharField(default='haiku', max_length=255),
        ),
    ]
