# Generated by Django 5.0.1 on 2024-06-01 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_useraccount_current_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='credits',
            field=models.IntegerField(default=200),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='current_model',
            field=models.CharField(default='gpt35', max_length=255),
        ),
    ]
