# Generated by Django 5.0.1 on 2024-06-06 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_useraccount_credits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_retrieval',
            field=models.BooleanField(default=True),
        ),
    ]
